# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-01 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_data',
            new_name='transaction_date',
        ),
    ]
