# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-02 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20200901_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugtype',
            name='type',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
